general.import = [
  "./Catppuccin-Mocha.toml"
]

[window]
decorations = "Buttonless"
  [window.padding]
  x = 0
  y = 0

  [window.dimensions]
  columns = 110
  lines = 38

[font]
size = 15

  [font.normal]
  family = "IosevkaCustomTerminal Nerd Font Mono"

[colors]
cursor = { text = "CellBackground", cursor = "#f5a97f" }

[cursor]
thickness = 0.25

  [cursor.style]
  shape = "Beam"
  blinking = "On"
